# Generated by Django 3.2 on 2021-04-13 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('birth', models.DateField(verbose_name='Date of Birth')),
                ('description', models.TextField(verbose_name='Description')),
                ('img', models.ImageField(upload_to='actors/', verbose_name='Image')),
                ('url', models.SlugField(blank=True, default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.SlugField(default=models.CharField(max_length=50, verbose_name='Category'), max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.SlugField(default=models.CharField(max_length=50, verbose_name='Category'), max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('tagline', models.CharField(default='', max_length=100, verbose_name='Tagline')),
                ('description', models.TextField(verbose_name='Description')),
                ('poster', models.ImageField(upload_to='movie/', verbose_name='Image')),
                ('year', models.DateField(verbose_name='Year')),
                ('country', models.CharField(max_length=50, verbose_name='Conuntry')),
                ('imdb_ratting', models.FloatField(default=5, verbose_name='iMDb Ratting')),
                ('world_premiere', models.DateField(default=datetime.date.today, verbose_name='World Premiere')),
                ('budget', models.PositiveIntegerField(default=0, help_text='Indicate in $', verbose_name='Budget')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, help_text='Indicate in $', verbose_name='Fees in USA')),
                ('fees_in_world', models.PositiveIntegerField(default=0, help_text='Indicate in $', verbose_name='Fees in world')),
                ('url', models.SlugField(blank=True, default='', max_length=100, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('actors', models.ManyToManyField(related_name='film_actor', to='myapp.Actor', verbose_name='Actors')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.category', verbose_name='Category')),
                ('directors', models.ManyToManyField(related_name='film_director', to='myapp.Actor', verbose_name='Director')),
                ('genres', models.ManyToManyField(to='myapp.Genre', verbose_name='Genres')),
            ],
        ),
        migrations.CreateModel(
            name='RattingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('text', models.TextField(verbose_name='Description')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie', verbose_name='Movie')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.reviews', verbose_name='Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Ratting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP adress')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie', verbose_name='Movie')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rattingstar', verbose_name='star')),
            ],
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='movies_shot/', verbose_name='Image')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie', verbose_name='Movie')),
            ],
        ),
    ]
