# Generated by Django 3.2 on 2021-04-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='url',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
