# Generated by Django 3.2 on 2021-04-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_genre_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(default='', max_length=200, verbose_name='Trailer'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default='', max_length=4, verbose_name='Year'),
        ),
    ]
